### ISSUE TITLE
latest release 4.2.5 is tagged with 4.2.6

### ISSUE THREAD

**Issue by solaegis** [45Drives/cockpit-file-sharing#115]
## Bug Info

**Describe the bug**
latest release 4.2.5 is tagged with 4.2.6 breaking the expected file naming standard.  This causes issues with [tteck](https://github.com/tteck)/[Proxmox](https://github.com/tteck/Proxmox) [cockpit](https://github.com/tteck/Proxmox/blob/57b9cde44d9b71115eae1e56d0c021b1496aad55/ct/cockpit.sh)'s installation

**To Reproduce**
1. Go to the releases section of this repo
2. look at the latest release named [Cockpit File Sharing 4.2.5](https://github.com/45Drives/cockpit-file-sharing/releases/tag/v4.2.6)
4. Notice it is tagged with 4.2.6

**Expected behavior**
The files for the latest release match the semantic tag.

**Screenshots**
![Screenshot 2024-10-30 at 4 36 49 PM](https://github.com/user-attachments/assets/fed8160d-492f-4f29-b0bd-1398e0e4ec31)

**Comment by bkelly16** [comment]
This is now fixed. Thank you for the report.

![image](https://github.com/user-attachments/assets/708938a3-873a-4bed-8c9b-674f8eb3ddaa)

**Comment by havardthom** [comment]
Hello, there is still a disconnect between github release tag `4.2.5` and filename tag `4.2.5-2` which is causing problems in ProxmoxVE helper script ref. https://github.com/community-scripts/ProxmoxVE/issues/157

I don't see the expected behavior in this issue being fulfilled

> Expected behavior
The files for the latest release match the semantic tag.
