### ISSUE TITLE
Cannot install in Fedora 34

### ISSUE THREAD

**Issue by jyxjjj** [45Drives/cockpit-file-sharing#18]
I saw the setup file and it seems to use EL8 like CentOS 8 when using Fedora any version.
Error infos: 
```
  - nothing provides /usr/libexec/platform-python needed by cockpit-file-sharing-1.0.0-1.el8.noarch
  - nothing provides /usr/libexec/platform-python needed by cockpit-file-sharing-2.1.0-1.el8.noarch
  - nothing provides /usr/libexec/platform-python needed by cockpit-file-sharing-2.2.0-1.el8.noarch
  - nothing provides /usr/libexec/platform-python needed by cockpit-file-sharing-2.2.1-1.el8.noarch
  - nothing provides /usr/libexec/platform-python needed by cockpit-file-sharing-2.3.0-1.el8.noarch
  - nothing provides /usr/libexec/platform-python needed by cockpit-file-sharing-2.3.1-1.el8.noarch
  - nothing provides /usr/libexec/platform-python needed by cockpit-file-sharing-2.4.0-3.el8.noarch
  - nothing provides /usr/libexec/platform-python needed by cockpit-file-sharing-2.4.1-1.el8.noarch
  - nothing provides /usr/libexec/platform-python needed by cockpit-file-sharing-2.4.1-2.el8.noarch
```

> dnf search nfs-kernel-server
> nothing  found.

> dnf install python3
> package python3-3.9.7-1.fc34.x86_64 has already installed.

> rpm -qa|grep nfs
> sssd-nfs-idmap-2.5.2-2.fc34.x86_64
> libnfsidmap-2.5.4-2.rc3.fc34.x86_64
> nfs-utils-2.5.4-2.rc3.fc34.x86_64
> libnfs-4.0.0-4.fc34.x86_64
> qemu-block-nfs-5.2.0-8.fc34.x86_64

**Comment by bkelly16** [comment]
@jyxjjj Looks like the issue is caused because the package was built on an el8 system. Any package built on an el8 (at least rocky, cant speak for true RHEL8 currently) system with "python3" specified will also have "platform-python" quietly added as a dep too. Where fedora does not have a package "platform-python" the packaged rpm fails to install. With that said the module will still function in fedora as all its needs is a functions python3 install, and the workaround is to install from source.

```
git clone https://github.com/45Drives/cockpit-file-sharing.git
cd cockpit-file-sharing/
make install
```
